-- ============================================
-- Area Code to Timezone Mapping Data
-- US area codes mapped to IANA timezones
-- ============================================
-- This migration seeds the area_code_timezones table with US area codes.
-- Data sourced from NANPA (North American Numbering Plan Administration)
-- ============================================

-- Clear existing data (for re-runs)
TRUNCATE TABLE area_code_timezones;

-- Insert area code mappings
INSERT INTO area_code_timezones (area_code, timezone, state, region) VALUES
-- Eastern Time Zone
('201', 'America/New_York', 'NJ', 'New Jersey'),
('202', 'America/New_York', 'DC', 'Washington DC'),
('203', 'America/New_York', 'CT', 'Connecticut'),
('205', 'America/Chicago', 'AL', 'Alabama'),
('206', 'America/Los_Angeles', 'WA', 'Washington'),
('207', 'America/New_York', 'ME', 'Maine'),
('208', 'America/Boise', 'ID', 'Idaho'),
('209', 'America/Los_Angeles', 'CA', 'California'),
('210', 'America/Chicago', 'TX', 'Texas'),
('212', 'America/New_York', 'NY', 'New York'),
('213', 'America/Los_Angeles', 'CA', 'California'),
('214', 'America/Chicago', 'TX', 'Texas'),
('215', 'America/New_York', 'PA', 'Pennsylvania'),
('216', 'America/New_York', 'OH', 'Ohio'),
('217', 'America/Chicago', 'IL', 'Illinois'),
('218', 'America/Chicago', 'MN', 'Minnesota'),
('219', 'America/Chicago', 'IN', 'Indiana'),
('220', 'America/New_York', 'OH', 'Ohio'),
('223', 'America/New_York', 'PA', 'Pennsylvania'),
('224', 'America/Chicago', 'IL', 'Illinois'),
('225', 'America/Chicago', 'LA', 'Louisiana'),
('228', 'America/Chicago', 'MS', 'Mississippi'),
('229', 'America/New_York', 'GA', 'Georgia'),
('231', 'America/New_York', 'MI', 'Michigan'),
('234', 'America/New_York', 'OH', 'Ohio'),
('239', 'America/New_York', 'FL', 'Florida'),
('240', 'America/New_York', 'MD', 'Maryland'),
('248', 'America/New_York', 'MI', 'Michigan'),
('251', 'America/Chicago', 'AL', 'Alabama'),
('252', 'America/New_York', 'NC', 'North Carolina'),
('253', 'America/Los_Angeles', 'WA', 'Washington'),
('254', 'America/Chicago', 'TX', 'Texas'),
('256', 'America/Chicago', 'AL', 'Alabama'),
('260', 'America/New_York', 'IN', 'Indiana'),
('262', 'America/Chicago', 'WI', 'Wisconsin'),
('267', 'America/New_York', 'PA', 'Pennsylvania'),
('269', 'America/New_York', 'MI', 'Michigan'),
('270', 'America/Chicago', 'KY', 'Kentucky'),
('272', 'America/New_York', 'PA', 'Pennsylvania'),
('276', 'America/New_York', 'VA', 'Virginia'),
('278', 'America/New_York', 'MI', 'Michigan'),
('279', 'America/Los_Angeles', 'CA', 'California'),
('281', 'America/Chicago', 'TX', 'Texas'),
('283', 'America/New_York', 'OH', 'Ohio'),
('301', 'America/New_York', 'MD', 'Maryland'),
('302', 'America/New_York', 'DE', 'Delaware'),
('303', 'America/Denver', 'CO', 'Colorado'),
('304', 'America/New_York', 'WV', 'West Virginia'),
('305', 'America/New_York', 'FL', 'Florida'),
('307', 'America/Denver', 'WY', 'Wyoming'),
('308', 'America/Chicago', 'NE', 'Nebraska'),
('309', 'America/Chicago', 'IL', 'Illinois'),
('310', 'America/Los_Angeles', 'CA', 'California'),
('312', 'America/Chicago', 'IL', 'Illinois'),
('313', 'America/New_York', 'MI', 'Michigan'),
('314', 'America/Chicago', 'MO', 'Missouri'),
('315', 'America/New_York', 'NY', 'New York'),
('316', 'America/Chicago', 'KS', 'Kansas'),
('317', 'America/New_York', 'IN', 'Indiana'),
('318', 'America/Chicago', 'LA', 'Louisiana'),
('319', 'America/Chicago', 'IA', 'Iowa'),
('320', 'America/Chicago', 'MN', 'Minnesota'),
('321', 'America/New_York', 'FL', 'Florida'),
('323', 'America/Los_Angeles', 'CA', 'California'),
('325', 'America/Chicago', 'TX', 'Texas'),
('326', 'America/New_York', 'OH', 'Ohio'),
('330', 'America/New_York', 'OH', 'Ohio'),
('331', 'America/Chicago', 'IL', 'Illinois'),
('332', 'America/New_York', 'NY', 'New York'),
('334', 'America/Chicago', 'AL', 'Alabama'),
('336', 'America/New_York', 'NC', 'North Carolina'),
('337', 'America/Chicago', 'LA', 'Louisiana'),
('339', 'America/New_York', 'MA', 'Massachusetts'),
('340', 'America/Virgin', 'VI', 'US Virgin Islands'),
('341', 'America/Los_Angeles', 'CA', 'California'),
('346', 'America/Chicago', 'TX', 'Texas'),
('347', 'America/New_York', 'NY', 'New York'),
('351', 'America/New_York', 'MA', 'Massachusetts'),
('352', 'America/New_York', 'FL', 'Florida'),
('360', 'America/Los_Angeles', 'WA', 'Washington'),
('361', 'America/Chicago', 'TX', 'Texas'),
('364', 'America/Chicago', 'KY', 'Kentucky'),
('380', 'America/New_York', 'OH', 'Ohio'),
('385', 'America/Denver', 'UT', 'Utah'),
('386', 'America/New_York', 'FL', 'Florida'),
('401', 'America/New_York', 'RI', 'Rhode Island'),
('402', 'America/Chicago', 'NE', 'Nebraska'),
('404', 'America/New_York', 'GA', 'Georgia'),
('405', 'America/Chicago', 'OK', 'Oklahoma'),
('406', 'America/Denver', 'MT', 'Montana'),
('407', 'America/New_York', 'FL', 'Florida'),
('408', 'America/Los_Angeles', 'CA', 'California'),
('409', 'America/Chicago', 'TX', 'Texas'),
('410', 'America/New_York', 'MD', 'Maryland'),
('412', 'America/New_York', 'PA', 'Pennsylvania'),
('413', 'America/New_York', 'MA', 'Massachusetts'),
('414', 'America/Chicago', 'WI', 'Wisconsin'),
('415', 'America/Los_Angeles', 'CA', 'California'),
('417', 'America/Chicago', 'MO', 'Missouri'),
('419', 'America/New_York', 'OH', 'Ohio'),
('423', 'America/New_York', 'TN', 'Tennessee'),
('424', 'America/Los_Angeles', 'CA', 'California'),
('425', 'America/Los_Angeles', 'WA', 'Washington'),
('430', 'America/Chicago', 'TX', 'Texas'),
('432', 'America/Chicago', 'TX', 'Texas'),
('434', 'America/New_York', 'VA', 'Virginia'),
('435', 'America/Denver', 'UT', 'Utah'),
('440', 'America/New_York', 'OH', 'Ohio'),
('442', 'America/Los_Angeles', 'CA', 'California'),
('443', 'America/New_York', 'MD', 'Maryland'),
('445', 'America/New_York', 'PA', 'Pennsylvania'),
('447', 'America/Chicago', 'IL', 'Illinois'),
('448', 'America/New_York', 'FL', 'Florida'),
('458', 'America/Los_Angeles', 'OR', 'Oregon'),
('463', 'America/New_York', 'IN', 'Indiana'),
('464', 'America/Chicago', 'IL', 'Illinois'),
('469', 'America/Chicago', 'TX', 'Texas'),
('470', 'America/New_York', 'GA', 'Georgia'),
('475', 'America/New_York', 'CT', 'Connecticut'),
('478', 'America/New_York', 'GA', 'Georgia'),
('479', 'America/Chicago', 'AR', 'Arkansas'),
('480', 'America/Phoenix', 'AZ', 'Arizona'),
('484', 'America/New_York', 'PA', 'Pennsylvania'),
('501', 'America/Chicago', 'AR', 'Arkansas'),
('502', 'America/New_York', 'KY', 'Kentucky'),
('503', 'America/Los_Angeles', 'OR', 'Oregon'),
('504', 'America/Chicago', 'LA', 'Louisiana'),
('505', 'America/Denver', 'NM', 'New Mexico'),
('507', 'America/Chicago', 'MN', 'Minnesota'),
('508', 'America/New_York', 'MA', 'Massachusetts'),
('509', 'America/Los_Angeles', 'WA', 'Washington'),
('510', 'America/Los_Angeles', 'CA', 'California'),
('512', 'America/Chicago', 'TX', 'Texas'),
('513', 'America/New_York', 'OH', 'Ohio'),
('515', 'America/Chicago', 'IA', 'Iowa'),
('516', 'America/New_York', 'NY', 'New York'),
('517', 'America/New_York', 'MI', 'Michigan'),
('518', 'America/New_York', 'NY', 'New York'),
('520', 'America/Phoenix', 'AZ', 'Arizona'),
('530', 'America/Los_Angeles', 'CA', 'California'),
('531', 'America/Chicago', 'NE', 'Nebraska'),
('534', 'America/Chicago', 'WI', 'Wisconsin'),
('539', 'America/Chicago', 'OK', 'Oklahoma'),
('540', 'America/New_York', 'VA', 'Virginia'),
('541', 'America/Los_Angeles', 'OR', 'Oregon'),
('551', 'America/New_York', 'NJ', 'New Jersey'),
('559', 'America/Los_Angeles', 'CA', 'California'),
('561', 'America/New_York', 'FL', 'Florida'),
('562', 'America/Los_Angeles', 'CA', 'California'),
('563', 'America/Chicago', 'IA', 'Iowa'),
('564', 'America/Los_Angeles', 'WA', 'Washington'),
('567', 'America/New_York', 'OH', 'Ohio'),
('570', 'America/New_York', 'PA', 'Pennsylvania'),
('571', 'America/New_York', 'VA', 'Virginia'),
('572', 'America/Chicago', 'OK', 'Oklahoma'),
('573', 'America/Chicago', 'MO', 'Missouri'),
('574', 'America/New_York', 'IN', 'Indiana'),
('575', 'America/Denver', 'NM', 'New Mexico'),
('580', 'America/Chicago', 'OK', 'Oklahoma'),
('585', 'America/New_York', 'NY', 'New York'),
('586', 'America/New_York', 'MI', 'Michigan'),
('601', 'America/Chicago', 'MS', 'Mississippi'),
('602', 'America/Phoenix', 'AZ', 'Arizona'),
('603', 'America/New_York', 'NH', 'New Hampshire'),
('605', 'America/Chicago', 'SD', 'South Dakota'),
('606', 'America/New_York', 'KY', 'Kentucky'),
('607', 'America/New_York', 'NY', 'New York'),
('608', 'America/Chicago', 'WI', 'Wisconsin'),
('609', 'America/New_York', 'NJ', 'New Jersey'),
('610', 'America/New_York', 'PA', 'Pennsylvania'),
('612', 'America/Chicago', 'MN', 'Minnesota'),
('614', 'America/New_York', 'OH', 'Ohio'),
('615', 'America/Chicago', 'TN', 'Tennessee'),
('616', 'America/New_York', 'MI', 'Michigan'),
('617', 'America/New_York', 'MA', 'Massachusetts'),
('618', 'America/Chicago', 'IL', 'Illinois'),
('619', 'America/Los_Angeles', 'CA', 'California'),
('620', 'America/Chicago', 'KS', 'Kansas'),
('623', 'America/Phoenix', 'AZ', 'Arizona'),
('626', 'America/Los_Angeles', 'CA', 'California'),
('628', 'America/Los_Angeles', 'CA', 'California'),
('629', 'America/Chicago', 'TN', 'Tennessee'),
('630', 'America/Chicago', 'IL', 'Illinois'),
('631', 'America/New_York', 'NY', 'New York'),
('636', 'America/Chicago', 'MO', 'Missouri'),
('640', 'America/New_York', 'NJ', 'New Jersey'),
('641', 'America/Chicago', 'IA', 'Iowa'),
('646', 'America/New_York', 'NY', 'New York'),
('650', 'America/Los_Angeles', 'CA', 'California'),
('651', 'America/Chicago', 'MN', 'Minnesota'),
('656', 'America/New_York', 'FL', 'Florida'),
('657', 'America/Los_Angeles', 'CA', 'California'),
('659', 'America/Chicago', 'AL', 'Alabama'),
('660', 'America/Chicago', 'MO', 'Missouri'),
('661', 'America/Los_Angeles', 'CA', 'California'),
('662', 'America/Chicago', 'MS', 'Mississippi'),
('667', 'America/New_York', 'MD', 'Maryland'),
('669', 'America/Los_Angeles', 'CA', 'California'),
('678', 'America/New_York', 'GA', 'Georgia'),
('680', 'America/New_York', 'NY', 'New York'),
('681', 'America/New_York', 'WV', 'West Virginia'),
('682', 'America/Chicago', 'TX', 'Texas'),
('689', 'America/New_York', 'FL', 'Florida'),
('701', 'America/Chicago', 'ND', 'North Dakota'),
('702', 'America/Los_Angeles', 'NV', 'Nevada'),
('703', 'America/New_York', 'VA', 'Virginia'),
('704', 'America/New_York', 'NC', 'North Carolina'),
('706', 'America/New_York', 'GA', 'Georgia'),
('707', 'America/Los_Angeles', 'CA', 'California'),
('708', 'America/Chicago', 'IL', 'Illinois'),
('712', 'America/Chicago', 'IA', 'Iowa'),
('713', 'America/Chicago', 'TX', 'Texas'),
('714', 'America/Los_Angeles', 'CA', 'California'),
('715', 'America/Chicago', 'WI', 'Wisconsin'),
('716', 'America/New_York', 'NY', 'New York'),
('717', 'America/New_York', 'PA', 'Pennsylvania'),
('718', 'America/New_York', 'NY', 'New York'),
('719', 'America/Denver', 'CO', 'Colorado'),
('720', 'America/Denver', 'CO', 'Colorado'),
('724', 'America/New_York', 'PA', 'Pennsylvania'),
('725', 'America/Los_Angeles', 'NV', 'Nevada'),
('726', 'America/Chicago', 'TX', 'Texas'),
('727', 'America/New_York', 'FL', 'Florida'),
('731', 'America/Chicago', 'TN', 'Tennessee'),
('732', 'America/New_York', 'NJ', 'New Jersey'),
('734', 'America/New_York', 'MI', 'Michigan'),
('737', 'America/Chicago', 'TX', 'Texas'),
('740', 'America/New_York', 'OH', 'Ohio'),
('743', 'America/New_York', 'NC', 'North Carolina'),
('747', 'America/Los_Angeles', 'CA', 'California'),
('754', 'America/New_York', 'FL', 'Florida'),
('757', 'America/New_York', 'VA', 'Virginia'),
('760', 'America/Los_Angeles', 'CA', 'California'),
('762', 'America/New_York', 'GA', 'Georgia'),
('763', 'America/Chicago', 'MN', 'Minnesota'),
('765', 'America/New_York', 'IN', 'Indiana'),
('769', 'America/Chicago', 'MS', 'Mississippi'),
('770', 'America/New_York', 'GA', 'Georgia'),
('772', 'America/New_York', 'FL', 'Florida'),
('773', 'America/Chicago', 'IL', 'Illinois'),
('774', 'America/New_York', 'MA', 'Massachusetts'),
('775', 'America/Los_Angeles', 'NV', 'Nevada'),
('779', 'America/Chicago', 'IL', 'Illinois'),
('781', 'America/New_York', 'MA', 'Massachusetts'),
('785', 'America/Chicago', 'KS', 'Kansas'),
('786', 'America/New_York', 'FL', 'Florida'),
('801', 'America/Denver', 'UT', 'Utah'),
('802', 'America/New_York', 'VT', 'Vermont'),
('803', 'America/New_York', 'SC', 'South Carolina'),
('804', 'America/New_York', 'VA', 'Virginia'),
('805', 'America/Los_Angeles', 'CA', 'California'),
('806', 'America/Chicago', 'TX', 'Texas'),
('808', 'Pacific/Honolulu', 'HI', 'Hawaii'),
('810', 'America/New_York', 'MI', 'Michigan'),
('812', 'America/New_York', 'IN', 'Indiana'),
('813', 'America/New_York', 'FL', 'Florida'),
('814', 'America/New_York', 'PA', 'Pennsylvania'),
('815', 'America/Chicago', 'IL', 'Illinois'),
('816', 'America/Chicago', 'MO', 'Missouri'),
('817', 'America/Chicago', 'TX', 'Texas'),
('818', 'America/Los_Angeles', 'CA', 'California'),
('820', 'America/Los_Angeles', 'CA', 'California'),
('828', 'America/New_York', 'NC', 'North Carolina'),
('830', 'America/Chicago', 'TX', 'Texas'),
('831', 'America/Los_Angeles', 'CA', 'California'),
('832', 'America/Chicago', 'TX', 'Texas'),
('838', 'America/New_York', 'NY', 'New York'),
('839', 'America/New_York', 'SC', 'South Carolina'),
('840', 'America/Los_Angeles', 'CA', 'California'),
('843', 'America/New_York', 'SC', 'South Carolina'),
('845', 'America/New_York', 'NY', 'New York'),
('847', 'America/Chicago', 'IL', 'Illinois'),
('848', 'America/New_York', 'NJ', 'New Jersey'),
('850', 'America/Chicago', 'FL', 'Florida'),
('854', 'America/New_York', 'SC', 'South Carolina'),
('856', 'America/New_York', 'NJ', 'New Jersey'),
('857', 'America/New_York', 'MA', 'Massachusetts'),
('858', 'America/Los_Angeles', 'CA', 'California'),
('859', 'America/New_York', 'KY', 'Kentucky'),
('860', 'America/New_York', 'CT', 'Connecticut'),
('862', 'America/New_York', 'NJ', 'New Jersey'),
('863', 'America/New_York', 'FL', 'Florida'),
('864', 'America/New_York', 'SC', 'South Carolina'),
('865', 'America/New_York', 'TN', 'Tennessee'),
('870', 'America/Chicago', 'AR', 'Arkansas'),
('872', 'America/Chicago', 'IL', 'Illinois'),
('878', 'America/New_York', 'PA', 'Pennsylvania'),
('901', 'America/Chicago', 'TN', 'Tennessee'),
('903', 'America/Chicago', 'TX', 'Texas'),
('904', 'America/New_York', 'FL', 'Florida'),
('906', 'America/New_York', 'MI', 'Michigan'),
('907', 'America/Anchorage', 'AK', 'Alaska'),
('908', 'America/New_York', 'NJ', 'New Jersey'),
('909', 'America/Los_Angeles', 'CA', 'California'),
('910', 'America/New_York', 'NC', 'North Carolina'),
('912', 'America/New_York', 'GA', 'Georgia'),
('913', 'America/Chicago', 'KS', 'Kansas'),
('914', 'America/New_York', 'NY', 'New York'),
('915', 'America/Denver', 'TX', 'Texas'),
('916', 'America/Los_Angeles', 'CA', 'California'),
('917', 'America/New_York', 'NY', 'New York'),
('918', 'America/Chicago', 'OK', 'Oklahoma'),
('919', 'America/New_York', 'NC', 'North Carolina'),
('920', 'America/Chicago', 'WI', 'Wisconsin'),
('925', 'America/Los_Angeles', 'CA', 'California'),
('928', 'America/Phoenix', 'AZ', 'Arizona'),
('929', 'America/New_York', 'NY', 'New York'),
('930', 'America/New_York', 'IN', 'Indiana'),
('931', 'America/Chicago', 'TN', 'Tennessee'),
('934', 'America/New_York', 'NY', 'New York'),
('936', 'America/Chicago', 'TX', 'Texas'),
('937', 'America/New_York', 'OH', 'Ohio'),
('938', 'America/Chicago', 'AL', 'Alabama'),
('940', 'America/Chicago', 'TX', 'Texas'),
('941', 'America/New_York', 'FL', 'Florida'),
('943', 'America/New_York', 'GA', 'Georgia'),
('945', 'America/Chicago', 'TX', 'Texas'),
('947', 'America/New_York', 'MI', 'Michigan'),
('949', 'America/Los_Angeles', 'CA', 'California'),
('951', 'America/Los_Angeles', 'CA', 'California'),
('952', 'America/Chicago', 'MN', 'Minnesota'),
('954', 'America/New_York', 'FL', 'Florida'),
('956', 'America/Chicago', 'TX', 'Texas'),
('959', 'America/New_York', 'CT', 'Connecticut'),
('970', 'America/Denver', 'CO', 'Colorado'),
('971', 'America/Los_Angeles', 'OR', 'Oregon'),
('972', 'America/Chicago', 'TX', 'Texas'),
('973', 'America/New_York', 'NJ', 'New Jersey'),
('978', 'America/New_York', 'MA', 'Massachusetts'),
('979', 'America/Chicago', 'TX', 'Texas'),
('980', 'America/New_York', 'NC', 'North Carolina'),
('983', 'America/Denver', 'CO', 'Colorado'),
('984', 'America/New_York', 'NC', 'North Carolina'),
('985', 'America/Chicago', 'LA', 'Louisiana'),
('986', 'America/Boise', 'ID', 'Idaho'),
('989', 'America/New_York', 'MI', 'Michigan');

-- Verify data loaded
SELECT COUNT(*) as area_codes_loaded FROM area_code_timezones;

-- ============================================
-- Done!
-- ============================================
SELECT 'Area code timezone data loaded successfully!' as status;
